name: Release OpenAPI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  GH_TOKEN: ${{ github.token }}
  #API_LIFECYCLE_SECRET: ${{ secrets.ApiLifecycleTrigger }}

jobs:
  Release:
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - uses: actions/checkout@v3
      - run: gh release create --generate-notes "${{ github.ref_name }}" "rfqs-api-v1.yml#OpenAPI"
      - run: |
          export GH_TOKEN=$API_LIFECYCLE_SECRET
          gh workflow run actions.yml -R "predic8/api-lifecycle-gateway"